### ISSUE TITLE
Unsupported KotlinClassMetadata of type null after update to Kotlin 1.5.20

### ISSUE THREAD

**Issue by PGliw** [beworker/magnet#101]
After Kotlin version was updated from 1.4.32 to 1.5.20 in an Android project, the Magnet throws an exception during Gradle build (that occurs in Magnet-generated class):
```
.../build/tmp/kapt3/stubs/main/.../.../.../.../.... . java:9 error:Unexpected compilation error, please file the bug at: https://github.com/beworker/magnet/issues. Message:
Unsupported KotlinClassMetadata of type null
public class ..... 
           ^
```
(irrelevant info was replaced with dots (...))

**Comment by beworker** [comment]
The fix is available in release 3.5 which is on the way.
