### ISSUE TITLE
Jacoco coverage

### ISSUE THREAD

**Issue by realdadfish** [beworker/magnet#67]
Magnet generates a couple of classes that count towards Jacoco's method and instruction coverage. Now it's possible to ignore those based on wildcards (e.g. `*MagnetIndexer`, `*MagnetFactory`), even nicer however would be if the types itself would be annotated as generated code, so they would be automatically ignored.

Newer Jacoco versions just need to find a class or runtime annotation that contains the string `Generated` in it's simple name to recognize ignorable types and go ahead. We have this here in our code base (Kotlin):

```
@Target(AnnotationTarget.CLASS, AnnotationTarget.FUNCTION, AnnotationTarget.CONSTRUCTOR)
@Retention(AnnotationRetention.BINARY) // this is translated to `RetentionPolicy.CLASS` in
annotation class Generated
```

**Comment by beworker** [comment]
+1 for the `Generated` annotation.

**Comment by realdadfish** [comment]
Thanks a lot!
