### ISSUE TITLE
@Classifier not applicable on factory methods

### ISSUE THREAD

**Issue by realdadfish** [beworker/magnet#71]
Version: 1.0-rc1

```java
const val APPLICATION = "application" // exists in different module

@Instance(type = FitnessTrackerManager::class)
fun createFitnessTrackerManager(@Classifier(APPLICATION) context: Context): FitnessTrackerManager = // ...
```

generates the following code

```java
public final class FitnessTrackerManagerKt {
    
    @org.jetbrains.annotations.NotNull()
    @magnet.Instance(type = path.to.FitnessTrackerManager.class)
    public static final path.to.FitnessTrackerManager createFitnessTrackerManager(@org.jetbrains.annotations.NotNull()
    @magnet.Classifier()
    android.content.Context context) {
        return null;
    }
}
```

which fails to compile with

```
e: path/to/FitnessTrackerManagerKt.java:12: error: annotation @Classifier is missing a default value for the element 'value'
    @magnet.Classifier()
    ^
```

**Comment by beworker** [comment]
I'll have a look into this on the weekend. If you had a possibility to add a failing test it would be a great help. Not a problem if you haven't though.

`MagnetProcessorTest.generateFactory_StaticMethodProvidesInnerClass()` is a good example for how to do it.

**Comment by realdadfish** [comment]
I'll try my best tonight :)

**Comment by beworker** [comment]
Thanks for the test @realdadfish! I took it over and formalized it a little bit. According to the test results Magnet is capable of generating proper code for static methods with classifier. Try to run `generateFactory_StaticMethodNeedsDependencyWithClassifier()` and see the results.

You must have run into another issue. Could you decompile your Kotlin file with `fun createFitnessTrackerManager()` method into Java and share it? I am particularly interested in how Kotlin generates Java code for the method. Then I will create a test for it as see what's going wrong there.

**Comment by realdadfish** [comment]
Hrm... I cannot seem to get it reproduced now any longer, both the factory method and the Factory calling this factory method seem to be generated correctly now...

```
public final class FitnessTrackerManagerKt {
   @Generated
   @Instance(
      type = FitnessTrackerManager.class
   )
   @NotNull
   public static final FitnessTrackerManager createFitnessTrackerManager(@Classifier("application") @NotNull Context context) {
      Intrinsics.checkParameterIsNotNull(context, "context");
      return FitnessTrackerManager.Companion.getInstance(context);
   }
}

@Generated
public final class FitnessTrackerManagerKtCreateFitnessTrackerManagerContextMagnetFactory extends InstanceFactory<FitnessTrackerManager> {
  @Override
  public FitnessTrackerManager create(Scope scope) {
    Context context = scope.getSingle(Context.class, "application");
    return FitnessTrackerManagerKt.createFitnessTrackerManager(context);
  }

  public static Class getType() {
    return FitnessTrackerManager.class;
  }
}
```

I'll close this for now until it pops up again.
