### ISSUE TITLE
Lazy construction

### ISSUE THREAD

**Issue by realdadfish** [beworker/magnet#75]
From time to time you come across use cases where you only need to instantiate objects when a certain condition is entered. Dagger supports this with `Lazy<Type>` injections or even by allowing `Provider<Type>`s to be injected, in case not a single, but multiple, state-holding instances are needed.

How would such a thing be possible in Magnet? At first I thought custom Factories could be used for this, but then I realized you'd only ever inject _what_ the factory _provides_ and not the factory itself.

Any ideas? :)

**Comment by beworker** [comment]
Magnet let you inject the scope in which the instance has been created as a dependency. The scope instance can be used to inject other instances when a condition is entered or even to create subscopes if needed. 

```kotlin
@Instance(type=SectionRenderer::class)
internal class MagnetSectionRenderer(
    private val scope: Scope
): SectionRenderer {

    override fun createViewHolder(parent: ViewGroup): SectionViewHolder<Section> {
        return scope.createSubscope {
            bind(layoutInflater.inflate(R.layout.section, parent, false), ROOT)
        }.getSingle<SectionViewHolder>()
    }
}
```

This is not exactly the `Lazy<T>` class you were asking for, but it let you achieve the same behavoir. Give it a try and let's see whether we need a dedicated lazy interface.

**Comment by realdadfish** [comment]
This looks very helpful - I guess one could abstract this a little bit, since injecting the `Scope` somewhere is kind of counter-intuitive in case you want to keep the the application independent from from the used DI tool. And since  `Scope` has functionality like `dispose()` in it as well, it could potentially break things even.

But it is certainly a start! Thanks for pointing me at it!

**Comment by realdadfish** [comment]
Could something like this work?

```java

interface Lazy {
    fun <T : Any> get(clazz: KClass<T>): T
}

@Instance(
    type = Lazy::class,
    factory = LazyFactory::class
)
internal class LazyImpl(private val scope: Scope) : Lazy {
    override fun <T : Any> get(clazz: KClass<T>): T = scope.getSingle(clazz.java)
}

class LazyFactory : Factory<Lazy> {
    override fun create(
        scope: Scope,
        type: Class<Lazy>,
        classifier: String,
        scoping: Scoping,
        instantiator: Factory.Instantiator<Lazy>
    ): Lazy {
        return instantiator.instantiate(scope)
    }
}
```

It would obviously be even cooler to have compile-time type safety here, but for that purpose this code would have to be generated individually.

**Comment by beworker** [comment]
> Could something like this work?
It could work and it doesn't need the custom factory, I think. You've basically created a functional interface for `getSingle()` function, which simply delegates the call to its scope, which is perfectly ok.

> This looks very helpful - I guess one could abstract this a little bit, since injecting the Scope somewhere is kind of counter-intuitive in case you want to keep the the application independent from from the used DI tool. And since Scope has functionality like dispose() in it as well, it could potentially break things even.

These were exactly my thoughts. One of the main principles of Magnet was to stay non intrusive with its API. I would want to omit any DI classes in the code at all when possible. Because `Scope` is already there and cannot be omitted (at least for now) I decided to expose it also as a dependency. But it's not generic one. It offers more than just a lazy getter.

Adding another `Lazy<T>` into Magnet and generate implementations for it similar to the one you wrote is easy task. But it add another Magnet dependency into the code.

How about using standard `kotlin.Lazy<T>` and if it gets injected as a dependency, wrap it into a simple lazy implementation like `val value = scope.getSingle(Type:class, "classifier")`? Magnet compiler needs to be extended then, but the change is really trivial.

**Comment by realdadfish** [comment]
I'm totally fine with using `kotlin.Lazy<T>`, but this would surely mean that this feature would be unavailable for Java projects, i.e. you'd draw in Kotlin as a source code dependency, no?

**Comment by beworker** [comment]
No, Java projects won't be able to use it unless they add `kotlin.Lazy<T>` to their classpath. There is no requests for lazy getter from any of Java projects yet anyway 😉 

I think it should work like this
```kotlin
@Classifier("classifier") val value: Lazy<T> = scope.getSingle(T::class.java, "classifier")
@Classifier("classifier") val value: Lazy<T>? = scope.getOptional(T::class.java, "classifier")
@Classifier("classifier") val value: List<Lazy<T>> = scope.getMany(T::class.java, "classifier")
```

**Comment by realdadfish** [comment]
Hrm... so you'd build in support for getting `Lazy` things into `Scope`? Or how should I understand this? Right now `getSingle` is defined as

```
@NotNull <T> T getSingle(@NotNull Class<T> type);
```

How should this return `Lazy<T>` if you cannot differentiate the calls?

**Comment by beworker** [comment]
Excuse my pseudocode 😄 I wanter to show _what_ will be wrapped by lazy instances for each cardinality. Changed `=` with `=>` in the original message. There will be no changes to the `Scope` interface.

The usage code will look like this

```kotlin
@Instance(type=BookRepository::class)
class BookRepository(private val Lazy<BookPersistence> persistence) {  
    fun store(book: Book) : Single<Result> = persistence.value.store(book)
}
```

**Comment by beworker** [comment]
> Or do you plan this as extension functions?

Lazy won't be "requestable" from the `Scope`. It will be injected as a dependency only.

**Comment by beworker** [comment]
There is one correction to the `List<Lazy<T>>` option. It can only be a lazy list `Lazy<List<T>>` and not a list of lazy elements as mentioned before because 

a) list items get resolved through `getOptional()` interface and null-values are removed from the list. Thus lazy items will have to be nullable too.
b) Because I would like to keep this as a kind of "kotlin extension", the logic cannot be moved into the `Scope` implementation, but should be built round it.

Final cardinality rules look like this
```kotlin
@Classifier("C") val value: Lazy<T> => scope.getSingle(T::class.java, "C")
@Classifier("C") val value: Lazy<T?> => scope.getOptional(T::class.java, "C")
@Classifier("C") val value: Lazy<List<T>> => scope.getMany(T::class.java, "C")
```

**Comment by realdadfish** [comment]
That's totally fine for me. I don't see a use case for List<Lazy<T>> anyways, either you want all items of a list lazy or none, if you want a single lazy dependency you should inject Lazy<T> directly. 

Am 5. März 2019 08:37:46 MEZ schrieb Sergej Shafarenka <notifications@github.com>:
>There is one correction to the `List<Lazy<T>>` option. It can only be a
>lazy list `Lazy<List<T>>` and not a list of lazy elements as mentioned
>before because 
>
>a) list items get resolved through `getOptional()` interface and
>null-values are removed from the list. Thus lazy items will have to be
>nullable too.
>b) Because I would like to keep this as a kind of "kotlin extension",
>the logic cannot be moved into the `Scope` implementation, but should
>be built round it.
>
>Final cardinality rules look like this
>```kotlin
>@Classifier("C") val value: Lazy<T> => scope.getSingle(T::class.java,
>"C")
>@Classifier("C") val value: Lazy<T?> =>
>scope.getOptional(T::class.java, "C")
>@Classifier("C") val value: Lazy<List<T>> =>
>scope.getMany(T::class.java, "C")
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beworker/magnet/issues/75#issuecomment-469572706

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by beworker** [comment]
It's same use case as for `getMay()` - when you want to find all available implementations of a certain interface - but you don't want to resolve all instances immediately but rather later in time, when some condition is reached.

**Comment by beworker** [comment]
I so used to Kotlin's comfort and absolutely forgot that Java generics have no idea about nullability. This means I cannot differentiate between `Lazy<T?>` and `Lazy<T>` to either call `getOptional()` or `getSingle()`. Stalemate for now.

**Comment by beworker** [comment]
There is a JetBrain's library for reading Kotlin metadata which might give more insides on generic's nullability. Moshi compiler uses it already and can be used as an example.

Library: https://github.com/JetBrains/kotlin/tree/master/libraries/kotlinx-metadata/jvm
Moshi example: https://github.com/square/moshi/pull/642

**Comment by realdadfish** [comment]
> This means I cannot differentiate between Lazy<T?> and Lazy<T> to either call getOptional() or getSingle()

Question is if this is actually a thing. If I want to lazy-initialize a heavy dependency, why should it be optional? What would be the use case there?

**Comment by beworker** [comment]
> Question is if this is actually a thing. If I want to lazy-initialize a heavy dependency, why should it be optional? What would be the use case there?

Consistency and functional correctness, I would say. 

Let's say we have just two cases `Lazy<T>` and `Lazy<T?>`. If both would use `getSingle()` then the second one will erroneously fail with NPE for an optional lazy value. If both would use `getOptional()` then the first one will fail with NPE when it will try to return a `null` value through not nullable lazy interface.

Even to support just `Lazy<T>` and fail compilation when user writes `Lazy<T?>` we have to be able to differentiate between those two at compilation time.

**Comment by beworker** [comment]
It looks good. Nullability flags can be read using `kotlinx-metadata-jvm` library 🔬 

To avoid possible instability I'm going to release current `3.0-rc1` as `3.0` and add this feature into upcoming `3.1` release, through alpha, beta etc. of course.

There will be also another feature added which is based on the same principle. I will add support for default values in injected constructors. Currently default values get overwritten by the values taken from the scope. Defaults are ignored.

**Comment by realdadfish** [comment]
I was wondering the other day how `Lazy` would cope with `Scoping.UNSCOPED`. As it is defined right now, `UNSCOPED` dependencies are not part of any `Scope`, thus created anew.

So in case I have this

```
@Instance(type = Unscoped::class, scope = Scoping.UNSCOPED)
class Unscoped

@Instance(type = Thing:class)
class Thing(unscoped1: Lazy<Unscoped>, unscoped2: Lazy<Unscoped>)
```

this would mean that `unscoped1.get() != unscoped2.get()`, right? This is somehow only one step away from a `Provider` kind of implementation I currently need, where class instances are created, query the current state, work on it and after that are thrown away.

I guess the current alternative is to inject the `Scope` itself, create a subscope, fetch and bind the (current) state to it and let `Unscoped` depend on it, but I somehow still dislike passing scope instances around in my code at that level... :)

**Comment by beworker** [comment]
> this would mean that unscoped1.get() != unscoped2.get(), right? 

Exactly way it is. If you want `unscoped1` and `unscoped2` to return the same instance, you need to scope them.

> This is somehow only one step away from a Provider kind of implementation I currently need, where class instances are created, query the current state, work on it and after that are thrown away.

I didn't get this one. As far as I can just `Provider` === `Scope.UNSCOPED`. In both cases, each time we call `get()` we receive a new instance. What is exactly required instead?

**Comment by beworker** [comment]
> I guess the current alternative is to inject the Scope itself, create a subscope, fetch and bind the (current) state to it and let Unscoped depend on it, but I somehow still dislike passing scope instances around in my code at that level... :)

Ah, you want to parametrize "parametrize" unscoped instances, query them, do some work and release them, do you?

**Comment by realdadfish** [comment]
> I didn't get this one. As far as I can just Provider === Scope.UNSCOPED. In both cases, each time we call get() we receive a new instance. What is exactly required instead?

Well, what I want is this:

```
class Foo(bars: Provider<Bar>) {
     fun bla(arg: Int) {
         bars.get().execute(arg)
     }
}
```

What I have to do now for this is this:

```
class Foo(scope: Scope) {
     fun bla(arg: Int) {
         scope.getSingle<Bar>().execute(arg)
     }
}
```

While the scope way of doing things is more powerful (as it allows me to create a subscope and potentially bind `arg` into it instead of giving it as a method parameter), it also means that the implementation now has a dependency on Magnet's `Scope` class.

**Comment by beworker** [comment]
I use this pattern at couple of places by turning it into factory one.

```kotlin
interface BarFactory {
    fun create(args: Args)
}

@Instance(
    type = BarFactory::class, 
    scoping = Scoping.DIRECT
)
internal class MagnetBarFactory(private val scope: Scope) : BarFactory {
    fun create(args: Args): Bar = 
        scope.createSubscope { bind(args) }.getSingle(Bar::class)
}
```

And then in Foo
```kotlin
class Foo(factory: BarFactory<Bar>) {
     fun bla(args: Args) = factory.create(args).execute()
}
```

Because `Bar.execute(args)` is called just once and then the instance gets disposed, it might make sense to move the arguments into the constructor. This makes the contract more clear.

There is no reason for adding a `Provider` interface into the library in my opinion, because there is no much difference in having a dependency on one interface of the library or another one. Dagger documentation says the following about `Provider` 

>Note: Injecting Provider<T> has the possibility of creating confusing code, and may be a design smell of mis-scoped or mis-structured objects in your graph. Often you will want to use a factory or a Lazy<T> or re-organize the lifetimes and structure of your code to be able to just inject a T. Injecting Provider<T> can, however, be a life saver in some cases. A common use is when you must use a legacy architecture that doesn’t line up with your object’s natural lifetimes (e.g. servlets are singletons by design, but only are valid in the context of request-specfic data).

I am actually agree with what they say and would suggest to implement a factory like the one above. `Bar` class can have a default scoping then too, which makes its scope more predictable. Hope this fits your needs.

Another question. Does this makes the need fo having Lazy<T> less urgent/important?

**Comment by realdadfish** [comment]
First things first, no, `Lazy<T>` is not urgent, we've worked around it by injecting `Scope` for now.

On the Factory injection, this looks actually more clean, indeed. Now I wish that Magnet could just automatically create the `MagnetBarFactory` for me, so I can just inject `BarFactory` everywhere :)

**Comment by beworker** [comment]
> On the Factory injection, this looks actually more clean, indeed. Now I wish that Magnet could just automatically create the MagnetBarFactory for me, so I can just inject BarFactory everywhere :)

Heh. I will think about this 😃

**Comment by beworker** [comment]
@realdadfish I just updated [github.com/beworker/g1](https://github.com/beworker/g1/tree/master/app) with 3.1-alpha1 and it worked just fine, including new lazy injections. Do you have any plans to update. It's ok if you don't, because you already have a solution leveraging `Scope` interface.

**Comment by realdadfish** [comment]
Thanks! I'll give it a try later on.
-- 
GPG-Key 0xCD45F2FD | Skype: realdeadfish | https://www.thomaskeller.biz
Please note that according to the EU law on data retention, information
on every electronic information exchange might be retained for a period
of six months or longer: http://www.vorratsdatenspeicherung.de/?lang=en
