### ISSUE TITLE
Support default values in constructors and methods in Kotlin

### ISSUE THREAD

**Issue by beworker** [beworker/magnet#77]
Magnet ignores default values while injecting parameters into constructors and methods in Kotlin. 
Expected behavior: Magnet does not inject values for parameters with defaults.

**Comment by realdadfish** [comment]
What is the rule in Magnet anyways here? Imagine I have provided `A` and `B`, which one would be the constructor Magnet would pick?

```kotlin
@Instance Foo(private val a: A, private val b: B) {
     constructor(a: A) : this(a, B())
}
```

IIRC `@Instance` is only allowed on static methods and types, not constructors, so I have no way to pick a specific constructor Magnet should use for construction, right?

**Comment by beworker** [comment]
> What is the rule in Magnet anyways here? Imagine I have provided A and B, which one would be the constructor Magnet would pick? 

> IIRC `@Instance` is only allowed on static methods and types, not constructors, so I have no way to pick a specific constructor Magnet should use for construction, right?

This is correct. Magnet will fail to compile because it expects a single non-private constructor. This was a deliberate design decision. The reason for is simpler annotation syntax (also for Kotlin) and enforced single-constructor design, which, in my opinion, is cleaner that multi-constructor one and Kotlin constructors confirm this.

This ticket is rather about default parameters in constructor. Let's take the example down below.

```kotlin
@Instance(type = GalleryScannerService::class)
internal class DefaultGalleryScannerService(
    mediaStoragePermissions: MediaStoragePermissions,
    mediaStorageObserver: MediaStorageObserver,
    mediaStorageSyncer: MediaStorageSyncer,
    computationScheduler: Scheduler = Schedulers.computation(),
    ioScheduler: Scheduler = Schedulers.io()
) : GalleryScannerService
```

It declares default values for `computationScheduler` and `ioScheduler` parameters. Current Magnet version overwrites those values with the ones from the scope, if they are available there. This ticket is about to respect given Kotlin defaults and keep them intact.

You might have a question why those two are in constructor at all. They are there for easier testing. There is no need to apply any special rules in tests. It's enough to provide `TestScheduler` or `Schedulers.trampoline()` to the instance and to test what ever needed, including debouncing and timeouts.

**Comment by realdadfish** [comment]
Ok, I see. I grouped together the various schedulers and more into a `SchedulerProvider`, of which I have a test implementation, so it is not much of a hassle for me to provide one instance of that provider in the root scope to have it available everywhere. I understand however if you inject individual instances of `Scheduler` you'd have to manually `@Classifier` them for injection, so it is easier to just use the static instance methods to return default values.

**Comment by beworker** [comment]
After more detailed analysis of the problem I realized that the constructor which sets default values in Kotlin is implemented as a synthetic method with Kotlin-specific parameters. Thus calling it properly from Java is practically impossible. The only option to respect default values in constructor would be to generate Kotlin code instead of Java code, which goes beyond the scope of this ticket.

**Comment by beworker** [comment]
Kotlin supports generation of overloaded Java constructors for a kotlin constructor with default arguments when `@JvmOverloads constructor` syntax is used. 

```kotlin
@Instance(type = TemplateObserver::class)
internal class DefaultTemplateObserver @JvmOverloads constructor(
    private val database: Database,
    private val marshaller: Marshaller,
    private val templateDao: TemplateDao,
    ioScheduler: Scheduler = Schedulers.io()
) : TemplateObserver { ... }
```
Because those constructors can be called from Java, Magnet will also be able to call them from the generated factories.
