### ISSUE TITLE
Lazy injection in Kotlin

### ISSUE THREAD

**Issue by realdadfish** [beworker/magnet#87]
I tried to use the new `Lazy` injection today and stumbled upon a code generation issue, where unless I annotate all `Lazy` injections with `@JvmSuppressWildcards`, Magnet will create invalid, non-compiling Java code like this:

```java
Lazy<? extends List<? extends Bar>> things = new SingleLazy(scope, ? extends List<? extends Bar>.class, "");
```

for a usage like this:

```kotlin
@Instance(type = Foo::class)
class Foo(bars: Lazy<List<Bar>>) { ... }
```

So yes, using `bars: Lazy<@JvmSuppressWildcards List<Bar>>` can be used as a workaround, but I think since you got plain `bars: List<Bar>` working as well, you could eventually do something about that :)

**Comment by beworker** [comment]
Thanks for reporting! I totally forgot that Kotlin generates wildcard parameter types. Fixed and will be released as `3.2-rc1` over the weekend.
