### ISSUE TITLE
3.3-rc3 packaging issue

### ISSUE THREAD

**Issue by realdadfish** [beworker/magnet#94]
The  `magnet-3.3-rc3.jar` has a packaging issue. It includes the file `mockito-extensions/org.mockito.plugins.MockMaker` (which was not present in Magnet 3.1 used previously) that makes my build fail with 

```
Execution failed for task ':my-module:transformResourcesWithMergeJavaResForDebugAndroidTest'.
> More than one file was found with OS independent path 'mockito-extensions/org.mockito.plugins.MockMaker'
```

Now when I add a `packagingOptions` attribute to remedy this issue (`exclude` or `pickFirst`), my tests crash, because the `mockito-android` MockMaker I have to use isn't configured at all any more (either because I `excluded` all instances of that file or because the inline mockmaker from your file's definition is picked `pickFirst`).

Could you please re-package without that file?

Many thanks!

**Comment by beworker** [comment]
It's fixed in `3.3-rc5`

**Comment by realdadfish** [comment]
Awesome, thank you! 

Am 24. Juli 2019 19:00:04 MESZ schrieb Sergej Shafarenka <notifications@github.com>:
>Closed #94.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beworker/magnet/issues/94#event-2507008032

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by beworker** [comment]
Sure. Would you please let me know whether it works fine for you that I can make a release.

**Comment by realdadfish** [comment]
Currently on vacation, will come back to this next week. 

Am 30. Juli 2019 17:40:40 MESZ schrieb Sergej Shafarenka <notifications@github.com>:
>Sure. Would you please let me know whether it works fine for you that I
>can make a release.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beworker/magnet/issues/94#issuecomment-516475370

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by beworker** [comment]
No problem man. Take your time and enjoy Norway ;)

**Comment by realdadfish** [comment]
It worked out nicely, thank you!
