### ISSUE TITLE
SelectorAttributeParser is treating nots as delimiters

### ISSUE THREAD

**Issue by mattbutlar** [beworker/magnet#99]
In SelectorAttributeParser the delimiter is defined as follows:

private val DELIMITER = Regex("[?!\\s|.]+")

This unfortunately matches on ! which means it won't even compile a selector using != or !in as it sees too many values in the string and even if it did compile it would not properly handle the nots since it would no longer have the !.

**Comment by beworker** [comment]
Thanks for reporting!

**Comment by beworker** [comment]
Fix is released in https://github.com/beworker/magnet/releases/tag/3.4-rc1
